version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${DOCKER_USERNAME}/ui
    environment:
      - POST_SERVICE_HOST
      - POST_SERVICE_PORT
      - COMMENT_SERVICE_HOST
      - COMMENT_SERVICE_PORT
    ports:
      - ${PUBLIC_TCP_PORT}:9292/tcp
    networks:
      - front_net
  post:
    image: ${DOCKER_USERNAME}/post
    environment:
      - POST_DATABASE_HOST
      - POST_DATABASE
    networks:
      - back_net
      - front_net
  comment:
    image: ${DOCKER_USERNAME}/comment
    environment:
      - COMMENT_DATABASE_HOST
      - COMMENT_DATABASE
    networks:
      - back_net
      - front_net
volumes:
  post_db:
networks:
  back_net:
  front_net:
