---
- name: Configure services
  hosts: all
  become: true
  tasks:

  - name: systemd services
    template:
      src: "templates/{{ item }}.service.j2"
      dest: "/etc/systemd/system/{{ item }}.service"
    with_items:
      - kube-apiserver
      - kube-controller-manager
      - kube-scheduler

  - name: run and enable services
    service:
      name: "{{ item }}"
      enabled: yes
      state: started
    with_items:
      - kube-apiserver
      - kube-controller-manager
      - kube-scheduler
