---
- name: Install k8s
  hosts: all
  become: true
  tasks:

  - name: install binaries
    get_url:
      url: https://storage.googleapis.com/kubernetes-release/release/v1.15.3/bin/linux/amd64/{{ item }}
      dest: /usr/local/bin
      mode: 0755
    with_items:
      - kube-apiserver
      - kube-controller-manager
      - kube-scheduler
      - kubectl
