---
- name: Install certificates k8s
  hosts: all
  become: true
  tasks:

  - name: create directory
    file:
      path: /var/lib/kubernetes/
      state: directory
      mode: 0750

  - name: copy certificates
    copy:
      src: files/pki/{{ item.src }}
      dest: "{{ item.dest }}"
    with_items:
      - {src: ca.pem, dest: "/var/lib/kubernetes/ca.pem"}
      - {src: ca-key.pem, dest: "/var/lib/kubernetes/ca-key.pem"}
      - {src: kubernetes.pem, dest: "/var/lib/kubernetes/kubernetes.pem"}
      - {src: kubernetes-key.pem, dest: "/var/lib/kubernetes/kubernetes-key.pem"}
      - {src: encryption-config.yaml, dest: "/var/lib/kubernetes/encryption-config.yaml"}
