kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: 0MXXc2OeZ8tyBUgVhSvyct3wMoQQMNEjUU3jrtuVOgI=
      - identity: {}
