version: '3.3'
services:
  ui:
    volumes:
      - ./ui:/app
  post:
    volumes:
      - ./post-py:/app
    command: puma --debug --w2
  comment:
    volumes:
      - ./comment:/app
    command: puma --debug --w2
