version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    build: ./ui
    image: ${DOCKER_USERNAME}/ui:${UI_VER}
    environment:
      - POST_SERVICE_HOST
      - POST_SERVICE_PORT
      - COMMENT_SERVICE_HOST
      - COMMENT_SERVICE_PORT
    ports:
      - ${PUBLIC_TCP_PORT}:9292/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${DOCKER_USERNAME}/post:${POST_VER}
    environment:
      - POST_DATABASE_HOST
      - POST_DATABASE
    networks:
      - back_net
      - front_net
  comment:
    build: ./comment
    image: ${DOCKER_USERNAME}/comment:${COMMENT_VER}
    environment:
      - COMMENT_DATABASE_HOST
      - COMMENT_DATABASE
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  back_net:
  front_net:
